# Default values: 'https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/theme-dark.toml'
# Path:
#   ~/.config/yazi/theme.toml        (Unix-like system)
#   %AppData%\yazi\config\theme.toml (Windows)
#
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# URL de themas (flavor) de la comunidad: 'https://github.com/yazi-rs/flavors/tree/main'
# Path:
#   ~/.config/yazi/flavor/<myflavor>/         (Unix-like system)
#   %AppData%\yazi\config\flavor\<myflavor>\  (Windows)
[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-mocha"
