# Default values: 'https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml'
# Path:
#   ~/.config/yazi/yazi.toml        (Unix-like systems)
#   %AppData%\yazi\config\yazi.toml (Windows)
#
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]

open_file = [
    # Para Windows
	#{ run = 'start "" %1', desc = "Open by defualt", for = "windows", orphan = true },
	{ run = 'cmd /c "%USERPROFILE%\.files\shell\cmd\bin\cmds\go_files_new_termtab.cmd" -p 2 %1', desc = "View in new TermTab (Parent folder)", for = "windows" },

    # Para Android (Termux)
	#{ run = 'termux-open "$1"', desc = "Open by default", for = "android" },

    # Para MacOS
	#{ run = 'open "$@"', desc = "Open by default", for = "macos" },

    # Para Linux y Unix
	#{ run = 'xdg-open "$1"', desc = "Open by default", for = "linux" },
	{ run = '${HOME}/.local/bin/go_files_new_termtab -p 2 "$1"', desc = "View in new TermTab (Parent folder)", for = "linux" },
	{ run = 'clear; exiftool "$1"; echo "Press enter to exit"; read _', desc = "Show metadata", for = "unix", block = true },
]

edit_txt = [
    # Para Windows
	{ run = '%EDITOR% %*', desc = "Edit in this TermTab", for = "windows", block = true },
	{ run = 'cmd /c "%USERPROFILE%\.files\shell\cmd\bin\cmds\go_files_new_termtab" -p 2 %1', desc = "Edit in new TermTab (Parent folder)", for = "windows" },
	#{ run = 'code %*', desc = "Edit with VSCode", for = "windows", orphan = true },

    # Para Android (Termux)
    # Para MacOS

    # Para Linux y Unix
	{ run = '${EDITOR:-vim} "$@"', desc = "Edit in this TermTab", for = "unix", block = true },
	{ run = '${HOME}/.local/bin/go_files_new_termtab -p 2 "$1"', desc = "Edit in new TermTab (Parent folder)", for = "linux" },
	#{ run = 'code "$@"', desc = "Edit with VSCode", for = "unix", orphan = true },
]

open_image = [
    # Para Windows
    # Para Android (Termux)
    # Para MacOS

    # Para Linux y Unix
	#{ run = 'krita "$1"', desc = "Open by Krita", for = "linux" },
	#{ run = 'gimp "$1"', desc = "Open by Gimp", for = "linux" },
]

play_video = [
    # Para Windows
	{ run = 'mediainfo %1 & pause', block = true, desc = "Show media info", for = "windows" },

    # Para Android (Termux)
    # Para MacOS

    # Para Linux y Unix
	{ run = 'mediainfo "$1"; echo "Press enter to exit"; read _', block = true, desc = "Show media info", for = "unix" },
]

open_folder = [
    # Para Windows
	{ run = 'cmd /c "%USERPROFILE%\.files\shell\cmd\bin\cmds\go_folder_new_termtab.cmd" -p 2 %1', desc = "Open in new TermTab", for = "windows" },
	#{ run = 'explorer /select,%1', desc = "Open in Explorer", for = "windows", orphan = true },
	#{ run = 'code %1', desc = "Open with VSCode", for = "windows", orphan = true },

    # Para Android (Termux)
    # Para MacOS

    # Para Linux y Unix
	{ run = '${HOME}/.local/bin/go_folder_new_termtab -p 2 "$1"', desc = "Open in new TermTab", for = "linux" },
	#{ run = 'nautilus --select "$1" &', desc = "Open in Explorer", for = "linux", orphan = true },
	#{ run = 'code "$1"', desc = "Open with VSCode", for = "unix", orphan = true },
]

reveal = [
    # Para Windows
	#{ run = 'explorer /select,%1', desc = "View in Explorer", for = "windows", orphan = true },
	{ run = 'cmd /c "%USERPROFILE%\.files\shell\cmd\bin\cmds\go_folder_new_termtab.cmd" -p 2 %1', desc = "Go parent folder in new TermTab", for = "windows" },

    # Para Android (Termux)
    # Para MacOS

    # Para Linux y Unix
	#{ run = 'nautilus --select "$1" &', desc = "View in Explorer", for = "linux", orphan = true },
	{ run = '${HOME}/.local/bin/go_folder_new_termtab -p 2 "$1"', desc = "Go parent folder in new TermTab", for = "linux" },

]

extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]

download = [
	{ run = "ya emit download --open %S", desc = "Download and open" },
	{ run = "ya emit download %S", desc = "Download" },
]



[open]
rules = [

	# Folder> Folder en Unix (Linux)
	{ mime = "inode/directory", use = [ "open_folder" ] },

	# Folder> Folder en Windows
	{ mime = "folder/local", use = [ "open_folder" ] },

    # File> Draw.IO (xml file that should be treated as binary)
    { url = "*.drawio", use = [ "open_file", "reveal" ] },

	# File> Text
	{ mime = "text/*", use = [ "edit_txt", "reveal" ] },

	# File> Empty file (new file create, for example, with 'touch')
	{ mime = "inode/empty", use = [ "edit_txt", "reveal" ] },

	# File> JSON
	{ mime = "application/{json,ndjson}", use = [ "edit_txt", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit_txt", "reveal" ] },

	# File> Image
	{ mime = "image/*", use = [ "open_file", "open_image", "reveal" ] },

	# File> Media
	{ mime = "{audio,video}/*", use = [ "open_file", "play_video", "reveal" ] },

	# File> Compressed file
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },

    # File> Office document
	{ mime = "application/{msword,ms-excel,ms-powerpoint}", use = [ "open_file", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.wordprocessingml.document", use = [ "open_file", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.spreadsheetml.sheet", use = [ "open_file", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.presentationml.presentation", use = [ "open_file", "reveal" ] },

	# Generic> Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download" },

	# Generic> Fallback
	{ url = "*", use = [ "open_file", "reveal" ] },

]
